### ISSUE TITLE
No sister Pipeline items for Pipeline 8 items

### ISSUE THREAD

**Issue by VermaBSI** [ben-garside/XCP#53] opened 2015-09-08 11:19 UTC
Hi,

Pipeline 8 items are generally expected alongside all items assigned to Pipelines other than 1 - thus referring to them as 'sister' items.

The sister items don't always appear in the collations list at the same time. One sometimes precedes  the other / or sometimes one doesn't seem to appear at all, like this current example:

No sister Pipeline 2 item for Pipeline 8 item 30273162 (see data in PROD env).

Just raising this in case sister items are being altogether missed. If a delay between sister items cannot be avoided then that's fine.

Thanks.

**Comment by ben-garside** [comment] 2015-09-21 12:57
There should not be a delay in the collation of either item as they are based on the same feed, i think this must have been due to the database issue we were having (#57) as both item are now in the system:

 - http://xcp.cs/item.php?xcpid=XCP8062914 
 - http://xcp.cs/item.php?xcpid=XCP3915568 

Do you know of any more examples that are missing so I can confirm what the error was. thanks :smile:

**Comment by VermaBSI** [comment] 2015-09-21 14:01
Thanks, I can confirm the same. No more examples (yet) - you can close this for now if you want and I can re-open if I need to.

**Comment by ben-garside** [comment] 2015-09-21 15:38
I have done some more analysis of these (https://bsi-group.box.com/analysisOfPiplines).

This shows that there are some PL8 with a 'sister' that has an error:

 - 30061582
 - 30061587
 - 30065799
 - 30065800
 - 30068494
 - 30068495
 - 30068603
 - 30068604
 - 30009185

And that PL6 items don't have a PL8 'sister':

 - 30322646
 - 30322651
 - 30324550
 - 30324562
 - 30324808
 - 30324809
 - 30325070
 - 30325173
 - 30325613
 - 30325644
 - 30325645

Could you have a quick look and see if any of these are actually things we need to worry about?

**Comment by VermaBSI** [comment] 2015-09-22 15:17
Hi,
Thanks for analysis. Examining it:

Re:  PL8 with a 'sister' that has an error:
Three are already in product with term-mappings, so are not of concern. The remaining UPIs 30061587
30068604
30068495
30065800
30061582
30009185
I would need more information about, i.e. to Standard IDs and titles to determine whether they should be for product (i.e. an SQL on these in SAP when you can - not urgent).

Re: PL6 items don't have a PL8 'sister':
Already converted and in product with term-mappings. 
NB. XCP contains a lot of data in the Collations tab (months old) that needs to be updated to stage 20+. I think this was because of all the sending I did before the 10.20 trigger for sending was up and running (I had just used the collations list to determine manual sends).

**Comment by VermaBSI** [comment] 2015-09-22 15:19
Sorry just realised those remaining UPIs are in the Collations Tab list with all further details. I'll add them to next sends as appropriate.

**Comment by VermaBSI** [comment] 2015-10-02 11:14
Hi Ben,

Reviewing data in XCP this morning, we are missing sister PLs for these PL8s:

XCP3684731_30009185
XCP5951046_30061587

NB. These are items also part of issue #73  

Thanks

**Comment by ben-garside** [comment] 2015-10-02 13:24
30009185s Complinav item (XCP2787558) is in the system, but there is an error in its pipeline allocation: ``92 - Incorrect materials returned... check project?``

30061587s Complinav item (XCP8397585) is in the system, but there is an error in its pipeline allocation: ``94 - Too many materials in project``

**Comment by VermaBSI** [comment] 2015-10-09 15:31
Hi Ben,

Just adding more examples of this problem seen in today's checking for sends:

XCP5359153_30281561_p8.zip

XCP0620126_30261091_p8.zip

XCP0476928_30276374_p8.zip

XCP1917968_30329879_p8.zip

XCP0032619_30282335_p8.zip

XCP5630554_30068604_p8.zip

XCP8867091_30068495_p8.zip

XCP4049451_30065800_p8.zip

XCP4685993_30061582_p8.zip

XCP3684731_30009185_p8.zip

XCP5951046_30061587_p8.zip

**Comment by ben-garside** [comment] 2015-10-09 15:45
Cheers. These are due to an issue with the collation job. It has been failing to copy content from the archive. i will raise a separate issue for this.

**Comment by VermaBSI** [comment] 2015-11-04 15:08
Hi Ben,

The present list of UPIs missing PL 8s, further to checking collations in XCP just now:

30314053             
30251610            
30267931         
30271309              

Thanks

**Comment by ben-garside** [comment] 2015-11-13 14:07
Hello

They are not missing, they are just not valid, none of the files could be found during collation

**Comment by VermaBSI** [comment] 2015-11-16 10:28
Hi Ben,

With reference to my earlier email responding to the list of collation errors you earlier provided:

It doesn't make sense that the files could not be found during collation, because XCP was able to find the source PDF for the sister PL in each case, and only needs that same source PDF for PL8. The few I have listed above have all been successfully collated as PL 2/4/7s - all we need for the PL 8 for each of these is the same source PDF. 

Does that makes sense :)?

**Comment by ben-garside** [comment] 2015-11-26 11:09
Closing this issue as it is now incorporated by #97

**Closed by ben-garside** 2015-11-26 11:09 UTC
Labels: collation tool, in progress
