### ISSUE TITLE
Adapt XCP to deliver collated files to Sentinel

### ISSUE THREAD

**Issue by hendersm** [ben-garside/XCP#124] opened 2016-02-08 15:36 UTC
Hi Ben, 

As discussed with IT can we amend XCP content delivery so it delivers into Sentinel so it can be sent over to Innodata.

Let me know if you need any further information.

Matt

**Comment by hendersm** [comment] 2016-02-08 15:37
Hi Ben, 

As discussed with IT can we amend XCP content delivery so it delivers into Sentinel so it can be sent over to Innodata.

Let me know if you need any further information.

Matt

**Comment by ben-garside** [comment] 2016-02-08 15:51
requirement to change the current FTP process to send files to new FTP location, code changes will be required so that the content in placed in the correct sub-folder (named by pipeline - tbc)

**Comment by VermaBSI** [comment] 2016-02-08 17:02
I'm happy to sit down and show you the test that Matt B and I did that successfully triggered the ingest of content into Sentinel from configured hot folders. And this was based on grouping packages into hot folders according to pipeline/batch ID that XCP generates, as you recommended.

**Comment by ben-garside** [comment] 2016-02-10 10:08
could someone please provide the batch (.bat) file that IT provided.

Cheers

**Comment by VermaBSI** [comment] 2016-02-10 10:18
Hi Ben am happy to do that, but before you start on this, please could we have a quick 5 min session at my desk so I can show you all the files, etc. and what we exactly did to load into Sentinel, just so I can be sure you're fully aware of the process we want XCP to intervene in on.

**Comment by VermaBSI** [comment] 2016-02-10 10:20
I am free all today, just let me know a convenient time for you in advance so I can prepare what I need to show you, thanks.

**Comment by VermaBSI** [comment] 2016-02-10 10:23
Just realised you're WFH today, I am tomorrow, so it will have to be Friday...in any case I've sent you a zip by email of all the files used in our test upload, which I will want to run through with you.

**Comment by ben-garside** [comment] 2016-02-10 10:28
I need the details in the batch file so i can make sure that the servers can connect, i am not starting any work on the requirement.

Please can you provide.

Cheers.

**Comment by ben-garside** [comment] 2016-02-10 13:15
@hendersm do have the batch file at all?

it can take time to get firewall changes made, so i would like to request sooner rather than later.

**Comment by hendersm** [comment] 2016-02-10 13:48
Hi Ben,

I’ve put this on a folder in Box and invited you to join.

Let me know if you have any issues.

Matt

---

Visit the BSI website at www.bsigroup.com

This email may contain confidential information and/or copyright
material. This email is intended for the use of the addressee only.
Any unauthorised use may be unlawful. If you receive this email
by mistake, please advise the sender immediately by using the
reply facility in your email software.

The British Standards Institution is incorporated by Royal Charter.

This email has been scanned for all known viruses.

**Comment by VermaBSI** [comment] 2016-02-10 14:02
Ben didn't you receive the zip file I sent you by email?

All files - including the batch file - were in there

**Comment by ben-garside** [comment] 2016-02-10 14:37
Thanks both, putting the request in now.

**Comment by ben-garside** [comment] 2016-02-16 12:01
@VermaBSI could you please have a look at the `xcp_dev_final` ftp server and check the config files to see if you see any obvious issues? Its just PL1 and 8 I think. Thanks.

**Comment by ben-garside** [comment] 2016-02-22 11:03
All, there is a delay in the ability to test this part of XCP, due to a mistake in the the RFC sent to attenda to make the required FW chnage. This has been corrected and we are just waiting for attenda to confirm.

Sorry about this delay.

**Comment by VermaBSI** [comment] 2016-02-22 11:05
Okay, thanks. Look forward to when it's confirmed so I can re-test.

**Comment by VermaBSI** [comment] 2016-02-22 11:53
Trying to attach the email from Yaqub indicating no config.xml files for your ease of reference:

From    Subject Received    Size    Categories  
Yaqub Rab   Sentinel errors 11:39   62 KB       reference

**Comment by VermaBSI** [comment] 2016-02-23 12:56
The send to Sentinel done at 12pm today has produced promising results in Sentinel, thanks, just a few things to correct:
1. The config.xml files have not been manifested quite correctly, errors in what XCP has written in **bold** below:

&lt;import&gt;
&lt;contentType&gt;BSI SDS&lt;/contentType&gt; &lt;baseWorkItemName&gt;**baseWorkItemName**&lt;/baseWorkItemName&gt;
&lt;packageGroup&gt;**2016-02-23**&lt;/packageGroup&gt;&lt;supplier&gt;Innodata&lt;/supplier&gt;&lt;reviewer&gt;varun.verma@bsigroup.com&lt;/reviewer&gt;&lt;pageCredit&gt;18&lt;/pageCredit&gt;
&lt;/import&gt;

Here is what a correct config.xml file should look like (compare bold entries to above):

&lt;import&gt;
    &lt;contentType&gt;ISOstsBSI&lt;/contentType&gt;
    &lt;baseWorkItemName&gt;**Pipeline_2**&lt;/baseWorkItemName&gt;
    &lt;packageGroup&gt;**BSI-02-CONV-PDF-ISOSTS-2015-11-30**&lt;/packageGroup&gt;
    &lt;supplier&gt;Innodata&lt;/supplier&gt;
    &lt;reviewer&gt;varun.verma@bsigroup.com&lt;/reviewer&gt;
    &lt;pageCredit&gt;80&lt;/pageCredit&gt;
&lt;/import&gt;

So &lt;baseWorkItemName&gt; should be **Pipeline_[pipeline no.]** and &lt;packageGroup&gt; should be the **batch ID** XCP generates.

Otherwise all very good :) - collation packages uploaded with all correct metadata, and successfully accessible when logging into Sentinel as Innodata.

If you could makes these changes to the config file manifestation and I will do a re-test.

**Comment by ben-garside** [comment] 2016-02-23 15:07
I have made the changes and deployed them to UAT. Please let me know if it has fixed the error you found.

**Comment by VermaBSI** [comment] 2016-03-18 13:02
As per our Lync conversations a few weeks back, and following your last comment, I will await for your confirmation that the new send stage 10.22 I've created for sending directly to Innodata is in place, so I can do a last send test to close this and other v1.5 bugs off.

Also, here is the new email template for anything sent via stage 10.20 to Sentinel:

---

Dear Innodata,

This is to inform you that new Work Packages have been assigned to you in Sentinel, for review for producing agreed XML outputs.

These Work Packages can be identified in Sentinel by **XCP_ID** and **Document_Filename (UPI)** indicated in the attached transmission sheet (these fields are concatenated the **Identifier** field in Sentinel). The transmission sheet also provides further details for each Work Package/UPI. 

Please could you confirm receipt of these files and get back on an estimated turnaround time (TAT) and cost by returning the transmission sheet. Following this we will confirm whether work should proceed.

Notes:
• **Innodata_Batch_ID** in the transmission sheet corresponds to **Package Group** in Sentinel. This reference just summarizes the Conversion Pipeline and sent date of the Work Package/UPI.
• The **Name** field in Sentinel indicates the **Conversion Pipeline** the work package needs to be processed through. (This same is indicated in the **Conversion_Pipeline** field in the transmission sheet).

Many thanks

---

**Comment by VermaBSI** [comment] 2016-03-18 15:25
Please could I just draw your attention to the following issue which would be good to fix alongside all this: #137

**Comment by ben-garside** [comment] 2016-03-21 16:34
Email wording has been updated.

**Comment by VermaBSI** [comment] 2016-03-21 17:22
Hi - everything has worked :D  (including PL 8 accidentally set to 10.20 being moved to stage 0.03, upload failure), EXCEPT the following corrections that would be good:
1. The transmission sheet attached on the email for PL 8s is the one for Sentinel deliveries, it should be the one FTPed directly with the PL 8s
2. The email for PL 8s should NOT be the new template provided above indicating Sentinel delivery - it should be the old one indicating FTP delivery
3. Please could the suffix **[zip filename]** be removed from the header of column C in the transmission sheet for Sentinel delivery route ONLY.

**Comment by ben-garside** [comment] 2016-03-21 17:52
I believe these are now fixed, can you check the emails from 17:50. Cheers

**Comment by VermaBSI** [comment] 2016-03-22 12:55
Thanks, all these fixes have been made.

However there are some further corrections to each email (this should definitely be the last):

**1. Email for Sentinel delivery route:**
a. The third paragraph 'Please could you confirm...' provided in the above template is missing, please could you add it **in bold** (like it is so in the PL 8 email template).
b. Please could you add the word 'in' before 'the Identifier...' (second paragraph).
c. Please could you change 'This same' to 'The same' (last bullet point under notes).
d. Please could you make the terms that are indicated bold in the above template, bold in the actual email that gets sent out.

**2. Email for PL 8s:**
Please simplify to this template (retaining bold formatting):

Dear Innodata,

This is to inform you that a new batch has been transferred to Innodata's FTP site, for review for producing agreed XML outputs. Attached is a transmission sheet detailing each Material (identified by UPI) in the batch.

**Please could you confirm receipt of these files and get back on an estimated turnaround time (TAT) and cost. Following this we will confirm whether work should proceed.**

Notes:
**Directory path: /TO INNO/2016-02-26**
• Materials are batched into a zip file named by Batch_ID (column C in the attached). Batch_ID confirms the Conversion_Pipeline that each Material within should be processed through (also indicated in column G in the attached). 

Many thanks

**Comment by ben-garside** [comment] 2016-03-22 13:45
@VermaBSI - all done :smile_cat:  

deployed to UAT ready to check.

**Comment by VermaBSI** [comment] 2016-03-22 14:23
Thanks, emails correct - you've just forgotten 1c. in my comment above, and also to make 'Identifier' bold in the Sentinel email; also was hoping the typo 'Innodata**\'**s FTP' in the PL 8 email would be rectified by the provision of a new overwriting template above :)

**Comment by ben-garside** [comment] 2016-03-22 14:34
Sorry about that, changes made... apart from the the typo you were hoping that would be rectified by the provision of a new overwriting template, as I don't know what it is :worried:

**Comment by ben-garside** [comment] 2016-03-22 14:36
done

**Comment by VermaBSI** [comment] 2016-03-22 14:45
There's a back-slash before the apostrophe (first line, first para)

**Comment by VermaBSI** [comment] 2016-03-29 11:23
Just to update where I understand we are with this following the testing last week, before our meeting today: 
**As per the latest send test done 22/03/2016 17:10 hrs:**
The Sentinel email send is all correct now, just need to ensure the pipeline 8 email is also being sent out (with the typo discussed above corrected), as this didn't happen.

**Comment by ben-garside** [comment] 2016-03-30 08:50
PL8 emails now being sent, tested in UAT and working as expected.

**Comment by VermaBSI** [comment] 2016-03-30 09:27
Thanks - I've just checked your test send, all fine, please could you run the final test of UAT again so I can affirm I've tested it through and it works too for a couple more PL 8s I've just set to 10.22.

**Comment by VermaBSI** [comment] 2016-03-30 10:03
Thanks, ALL is correct now - and I tested the adding of TAT and est. cost to these latest sent items, I really like the separation and data-type restriction of them, works really well, plus the skipping, etc. all worked.

Could I ask you to run the UAT final test send once again for a VERY LAST (promise) test including PL 8 plus Sentinel sends, so I can definitely sign off the separation of TAT and est. cost actions?

**Comment by ben-garside** [comment] 2016-03-30 10:44
running....

**Comment by VermaBSI** [comment] 2016-03-30 11:31
Okay, everything's finally correct,  :D

Thank you. I am now happy for UAT to be pushed to Live so we can get some first pl 2s to Innodata through Sentinel by the end of this week (issue #120 can wait if it needs to) - BUT first I need to let Innodata know in advance, and clear out all old files out of Sentinel, so please wait until I give the go ahead before pushing anything to Live.

**Closed as completed by VermaBSI** 2016-03-30 11:31 UTC
Labels: enhancement
