### ISSUE TITLE
Store Batch_Id in BATCH_DATA against relevant XCP IDs

### ISSUE THREAD

**Issue by odeclas** [ben-garside/XCP#72] opened 2015-09-24 15:02 UTC
After each send, record the batch ID for that set in BATCH_DATA for the relevant XCP IDs.

The intended use case is for a user to be able to add data (such as TAT or cost) as an Action to the Batch, and not the Item. Items would be linked by that batch_id, and would display this information on both the activity tracker detail sheet and in reports.

**Comment by VermaBSI** [comment] 2016-02-03 11:21
Isn't this a duplicate of #90? Am closing...

**Closed by VermaBSI** 2016-02-03 11:21 UTC
Labels: feature request, uat
